# --- 1. 主站：问卷平台 (夏目蓝) ---
server {
    listen 3001;
    server_name natsumeai.icu; # 换成你的尊贵域名

    # 保持你优秀的 Gzip 配置
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    location / {
        root /usr/share/nginx/html; # 对应问卷 B 端的 dist
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# --- 2. 副站：爱彼迎项目 ---
server {
    listen 3002;
    server_name natsumeai.icu;

    location / {
        root /usr/share/nginx/airbnb; # 这个路径对应 docker-compose 挂载的路径
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}