name: Deploy Client-B

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/wenjuan-platform/frontend-b
            git remote set-url origin git@github.com:Cabbage-2023/wenjuan-frontend.git || true
            
            git fetch --all && git reset --hard origin/main
            
            # 写入环境变量 (注意这里去掉外层的多余引号)
            echo "${{ secrets.ENV_PROD }}" > .env.production
            
            cd ~/wenjuan-platform
            docker compose build --no-cache client-b
            docker compose up -d client-b
            docker image prune -f